# deploy with:
# mkdocs gh-deploy
site_name: W&S Elferplatz Combinations rendering Documentation
theme:
  name: material
nav:
  - Home: Blender Scripting/W&S - Blender scripting documentation.md
  - Blender Scripting:
      - Configurations:
          - Combinations Rendering: Combinations Rendering.md
          - Configurations Generation: Configurations Generation.md
      - Headless Rendering:
          - Headless Rendering: Headless Rendering.md
          - Script Loading: Script loading.md
          - Using Command Line Arguments: Using command line arguments.md
      - Scripting:
          - Blender to Script: Blender to Script.md
          - Environment Rendering: Environment Rendering.md
          - File Structure: File Structure.md
          - Memory Probing: Memory Probing.md
          - Render Settings: Render Settings.md
  - Plannings:
      - Kennzeichen Konfigurator: Plannings/Kennzeichen-Konfigurator.md


